# Conexão com o seu banco local
spring.datasource.url=jdbc:postgresql://localhost:5432/biblerank
spring.datasource.username=postgres
spring.datasource.password=161105

# Configurações do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Inicialização dos Livros (import.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.thymeleaf.cache=false