-- VELHO TESTAMENTO
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Gênesis', 50, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Êxodo', 40, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Levítico', 27, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Números', 36, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Deuteronômio', 34, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Josué', 24, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Juízes', 21, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Rute', 4, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('1 Samuel', 31, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('2 Samuel', 24, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('1 Reis', 22, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('2 Reis', 25, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('1 Crônicas', 29, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('2 Crônicas', 36, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Esdras', 10, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Neemias', 13, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Ester', 10, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Jó', 42, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Salmos', 150, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Provérbios', 31, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Eclesiastes', 12, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Cantares', 8, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Isaías', 66, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Jeremias', 52, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Lamentações', 5, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Ezequiel', 48, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Daniel', 12, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Oséias', 14, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Joel', 3, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Amós', 9, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Obadias', 1, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Jonas', 4, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Miquéias', 7, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Naum', 3, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Habacuque', 3, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Sofonias', 3, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Ageu', 2, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Zacarias', 14, 'Velho');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Malaquias', 4, 'Velho');

-- NOVO TESTAMENTO
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Mateus', 28, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Marcos', 16, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Lucas', 24, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('João', 21, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Atos', 28, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Romanos', 16, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('1 Coríntios', 16, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('2 Coríntios', 13, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Gálatas', 6, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Efésios', 6, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Filipenses', 4, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Colossenses', 4, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('1 Tessalonicenses', 5, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('2 Tessalonicenses', 3, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('1 Timóteo', 6, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('2 Timóteo', 4, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Tito', 3, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Filemom', 1, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Hebreus', 13, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Tiago', 5, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('1 Pedro', 5, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('2 Pedro', 3, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('1 João', 5, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('2 João', 1, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('3 João', 1, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Judas', 1, 'Novo');
INSERT INTO livro (nome, total_capitulos, testamento) VALUES ('Apocalipse', 22, 'Novo');